FROM mcr.microsoft.com/mssql/server:2019-latest

COPY data /var/opt/mssql/data
COPY log /var/opt/mssql/log
COPY backup /var/opt/mssql/backup
COPY secrets /var/opt/mssql/secrets
COPY tmp /var/opt/mssql/tmp
COPY host /host
